### ISSUE TITLE
Problem in sending audios of large size

### ISSUE THREAD

**Issue by manzoorwanijk** [irazasyed/telegram-bot-sdk#135] opened 2016-04-14 05:07 UTC
Hi,
I use the SDK Standalone. Everything works fine, but when I try to send an audio of bigger size (I tried >16MB, >30mb), it sends the same audio multiple times to the user. I reported the issue to Telegram BotSupport, they replied, **"The upload of the audio file takes too long and the webhook times out before your server responds with code 200. All long tasks, for example file uploads should be done asynchronously, after the answer to webhook was already sent."** 
Then I tried to send the audio using an Asynchronous call. But it was the same - sending the audio multiple times to the same user. This the code that I use in my hook.php, :
```
require 'vendor/autoload.php';
use Telegram\Bot\Api;

$telegram = new Api('My Bot Token');

$audio = 'audio.mp3'; //32 MB
$performer = 'Some Artist';
$title = 'Talking to kids';
$duration = 2138; //in seconds

$response = $telegram
->setAsyncRequest(true)
->sendAudio([
  'chat_id' => $chat_id, 
  'audio' => $audio,
  'duration' => $duration,
  'performer' => $performer,
  'title' => $title
]);
```
I also tried to make all the API calls asynchronous, by using `$telegram = new Api('BOT TOKEN', true);`, but that also did't work. Then I set up the log file for incoming updates via hook, Telegram sends me the updates multiple times, that being the reason for the problem. But this perhaps is because the webhook timesout and then it tries to trigger again to get the response.

What I want to achieve?
1. Get the user message text,
2. Process it
3. Send the user an audio according to the message
4. Get the final response from Telegram API to get the file_id for future use.

Is the 4th step possible when making an asynchronous API call?

**Comment by irazasyed** [comment] 2016-04-14 23:20
Hi, I'll look into this issue soon. Been very busy to get the V3 out.

Allow me some time to look into it. As far as point 4 is concerned, it's not possible to do that. If I think of an alternate way, I'll let you know here.

**Comment by manzoorwanijk** [comment] 2016-04-15 02:59
Yeah, I can understand. Thank you very much :)

**Comment by irazasyed** [comment] 2016-04-16 02:56
Hi @manzoorwanijk I just tested this today with about 24 MB sized file and in async mode. It seems to work just fine as expected.

Like Telegram mentioned, your webhook should respond with status code 200 but your webhook file does not output anything as I can see.

So what you can do is, just simply do `exit('Done');` at the end of the file and it'll automatically respond the status as 200 to Telegram while the file is being uploaded in the background for you. Once it's uploaded, it should arrive.

The only time multiple messages or files show up is when Telegram does not get a 200 response, so I re-requests the webhook with the same update object. When this happens, your webhook takes it as a new request and is processing it normally.

Try it out and let me know.

I'll keep this ticket open for another 1-2 days before closing it if i don't hear any update from your end. Thanks and hopefully it'll work for you.

**Comment by manzoorwanijk** [comment] 2016-04-16 07:27
Thank you for your response. I did exactly as you said, added `exit('Done');` at the end (also tried `exit();`), but it didn't work. This time also I tried to make all the calls asynchronous - `$telegram = new Api('BOT TOKEN', true);` but that didn't work either. It again receives the update object multiple times, so sends the file multiple times as well. It works fine upto 15MB in my case but as the size gets bigger, the problem starts.
I'm not a private server user, rather I use a shared premium hosting. May be your server has a high speed that responded well in time to the webhook.
I also tried using cURL, but didn't work :(

**Comment by irazasyed** [comment] 2016-04-16 08:53
No problem.

The problem you're facing is quite weird and is mostly due to your end resources such as your server which might be causing trouble.

I'd recommend you spin up a droplet on [DigitalOcean](https://www.digitalocean.com), A basic one will do just fine and test this script there. Their servers are good and we use it too.

If you still have the issues after testing with DigitalOcean, then we'll have to dig deeper into this issue and see what's causing this problem. I can confirm it's not SDK for sure.

I will give a try with even larger file than what i used to test already but i still believe that is not the problem at all.

I'm closing this ticket for now but feel free to create a new one if it continues to fail or open this one.

**Closed by irazasyed** 2016-04-16 08:53 UTC

**Comment by jonnywilliamson** [comment] 2016-04-16 10:13
This sounds like a classic case for the use of a queue system...

Just tried a 38 meg audio file on my server using the bot and it was delivered first go.

![image](https://cloud.githubusercontent.com/assets/2513663/14580430/2808fd90-03c4-11e6-9694-b46bc1c8d0cf.png)

**Comment by jonnywilliamson** [comment] 2016-04-16 10:28
>This time also I tried to make all the calls asynchronous - $telegram = new Api('BOT TOKEN', true); but that didn't work either. It again receives the update object multiple times,


Also something doesn't seem right about this.

So the user sent your bot a command (which should return an audio file). However at the moment your server is timing out because it can't upload the file quickly enough to telegram's server. 

That means a 200 response was never sent in reply to the webhook update and so telegram thinks you never got the command in the first place and so retries again a few mins/sec later.

However, it doesn't appear that you actually managed to send the file asyc. I've just tried it here and again, I instantly got my 200 reponse and about 20 secs later the file arrived.

Are you getting an timeout errors in your log files? I'm wondering if the upload is taking so long on your server that the php script then timesout.

I wonder if you could try it again (async), using http://php.net/manual/en/function.set-time-limit.php  set_time_limit(300) or similar in your file.

**Comment by manzoorwanijk** [comment] 2016-04-20 16:03
Yes, it seems like 200 response is never sent even after `->setAsyncRequest(true)`
I tried to comment line 57 `Promise\unwrap(self::$promises);` in HttpClients/GuzzleHttpClient.php, but that prevented the file from being uploaded.

But this is what solved my problem:
http://stackoverflow.com/questions/15273570/continue-processing-php-after-sending-http-response

Thank you for your answers
