### ISSUE TITLE
How to change the default request values of BASE_BOT_URL and the handler's verify option?

### ISSUE THREAD

**Issue by ghost** [irazasyed/telegram-bot-sdk#941] opened 2022-04-20 09:14 UTC
Hello everyone,

In order to connect my bot to the [local bot API server](https://core.telegram.org/bots/api#using-a-local-bot-api-server) and in order to turn curl's SSL verify_host and verify_peer off, how can I **change the default request values of BASE_BOT_URL and the handler's verify option**, not hard coding?

I know that I can change the BASE_BOT_URL constant in [**TelegramClient class**](https://github.com/irazasyed/telegram-bot-sdk/blob/f5c835850a34049f4af9891ea34716bd79657dd0/src/TelegramClient.php#L17). And I know that I can change the verify option of my request handler to be false in [**guzzle's CurlFactory class**](https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlFactory.php#L353). But, I'm **not interested in hard-coding or overriding** these vendor files to avoid any update challenges in the future. I am more interested in something like [longman/telegram-bot's setCustomBotApiUri function](https://github.com/php-telegram-bot/core/blob/develop/src/Request.php#L324). The closest I could get is working with [**setHttpClientHandler** function](https://github.com/irazasyed/telegram-bot-sdk/blob/f5c835850a34049f4af9891ea34716bd79657dd0/src/Traits/Http.php#L48), but I'm having trouble how to work with that.

Isn't a function for changing these defaults necessary in such libraries?

Appreciate any help

P.S. I am using irazasyed/telegram-bot-sdk:^3.6 in my laravel:^9.2 app.

**Comment by bloomlive** [comment] 2022-04-20 11:57
[How about you use the method that uses the constant instead?](https://github.com/irazasyed/telegram-bot-sdk/blob/439552ebbbbbb9051f435c6556bb1c2ba5771425/src/TelegramClient.php#L115)

**Comment by RoliJ** [comment] 2022-04-20 17:12
Duplicate of #942

**Comment by RoliJ** [comment] 2022-04-20 17:16
> [How about you use the method that uses the constant instead?](https://github.com/irazasyed/telegram-bot-sdk/blob/439552ebbbbbb9051f435c6556bb1c2ba5771425/src/TelegramClient.php#L115)

Thank you @bloomlive for the reply. I opened this issue before I delete my account, and to be able to track down the issue, I opened it again. I would be happy if someone could close this and we move the discussion to #942 .

**Closed as completed** 2023-03-11 00:38 UTC
