### ISSUE TITLE
conflict with many packages, because use guzzle ~6.0

### ISSUE THREAD

**Issue by vadimwe** [irazasyed/telegram-bot-sdk#57] opened 2015-11-24 18:56 UTC
conflict with many packages, because use guzzle ~6.0

**Comment by irazasyed** [comment] 2015-11-24 22:01
Can you explain what's wrong and post your composer json?

**Comment by vadimwe** [comment] 2015-11-25 06:43
"require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.1.*",
        "barryvdh/laravel-debugbar": "^2.0@dev",
        "laravelcollective/html": "~5.0",
        "filp/whoops": "^1.2@dev",
        "guzzlehttp/guzzle": "~5.0",
        "abmti/laravel-scaffold-generate": "dev-master",
        "torann/geoip": "dev-master",
        "intervention/image": "^2.3@dev",
        "intervention/imagecache": "dev-master",
        "roumen/sitemap": "dev-master",
        "laravel/socialite": "^3.0@dev"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "phpspec/phpspec": "~2.1"
    },

cli:

composer require irazasyed/telegram-bot-sdk ^1.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: guzzlehttp/guzzle[6.1.x-dev, 5.3.0].
    - Can only install one of: guzzlehttp/guzzle[6.1.x-dev, 5.3.0].
    - Can only install one of: guzzlehttp/guzzle[6.1.x-dev, 5.3.0].
    - irazasyed/telegram-bot-sdk v1.0.0 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.1.x-dev].
    - Installation request for irazasyed/telegram-bot-sdk ^1.0 -> satisfiable by irazasyed/telegram-bot-sdk[v1.0.0].
    - Installation request for guzzlehttp/guzzle == 5.3.0.0 -> satisfiable by guzzlehttp/guzzle[5.3.0].

**Comment by irazasyed** [comment] 2015-11-25 18:30
I see you're requiring `"guzzlehttp/guzzle": "~5.0"` this is where the problem is. This package depends on Guzzle 6.0. You need to either remove that from your composer or update its version to match the package's version. This is something unrelated to this package though. So I'll have to close this ticket now! Hope that helps.

**Closed by irazasyed** 2015-11-25 18:30 UTC
