### ISSUE TITLE
Async Requests not working

### ISSUE THREAD

**Issue by codengine** [irazasyed/telegram-bot-sdk#12] opened 2015-07-20 14:12 UTC
Hi, I was trying to use asynchronous requests using the following setup:

-Windows 7 64 Bit
-PHP 5.6.3 (32 Bit)
-Telegram Bot SDK 0.2.4
-Guzzle 6.0.2

Plain sending messages using this
```php
$telegram->setAsyncRequest(true)
    ->sendMessage($message->get('chat')->get('id'), 'Test');
```

does not work although requests without async **do** work. I don't know if this is Windows related.
There is no error message nor exception, there is just nothing being sent to the Telegram server.

With best regards,

Stefan Hueg

**Comment by irazasyed** [comment] 2015-07-20 14:49
Hi @codengine,

I'll look into this now and get back to you soon.

Thanks!

Syed

**Comment by irazasyed** [comment] 2015-07-20 14:58
I just tested this and it seems to be working fine!

Not sure what the problem is with yours. I tested it on Ubuntu btw.

Can you make sure the chat id is correct and that you're having that id?

Keep in mind, Async requests don't return anything, since they don't wait for the response.

**Comment by codengine** [comment] 2015-07-20 15:35
Strange, it seems that this is related to GuzzleHTTP, as this simple code also does not work:

```php
$start = microtime(true);
$client = new GuzzleHttp\Client();
echo $start - microtime(true). " before\n";

$response = $client->getAsync('http://guzzle.readthedocs.org/en/latest/index.html', ['future' => true, 'verify' => false]);
echo $start - microtime(true). " after\n";
$response->then(function($response) use ($start){
    echo $start - microtime(true). " response\n";
});
echo $start - microtime(true). " end\n";
sleep(5);
die();
```

It will never show a response. I could not find futher information about this topic, but I will try it later on my other machine running PHP x64 with nginx.

**Comment by codengine** [comment] 2015-07-20 16:41
As you can see, I'm using a long-running PHP script. Might that be related to the issue? I noticed that you were using unwap() on destruct(), which will execute all promises at once.

I have to admit that I'm not that experienced with Guzzle and Async Requests and documentation is hard to find.

What I was trying to to is just firing the requests and then get the next list of updates. It seems as if this is not possible.

**Comment by irazasyed** [comment] 2015-07-22 00:32
Well, I'm not sure about windows. But it works fine on *nix based OSes.

Also, what you're trying to do above won't work because of the way its designed. It won't return anything.

You need to call `$response->wait();` for it to work.

**Comment by irazasyed** [comment] 2015-07-22 00:36
BTW Once you use `$telegram->setAsyncRequest(true)` all the next requests would be async. So you need to set it to false after making one request async, So the next requests would continue to be sync.

For now I'm closing this ticket since i can't reproduce the issue from my end nor i have any idea how you're running the script (From initialising to the end).

**Closed by irazasyed** 2015-07-22 00:36 UTC

**Comment by codengine** [comment] 2015-07-22 00:49
I think I got it. The way you've implemented the promises only works if the the whole script is terminated (and therefore unwrap() is executed, processing all messages).

What I was trying to do was setting up a long running, polling script which processes and sends messages in a loop, but this is currently not possible.

I dont have any possibility to "flush" the promise queue, therefore nothing is getting sent.

**Comment by irazasyed** [comment] 2015-07-22 01:23
Yep, That's right.

As for processing the messages, I'm not sure why you would want to do that?

Why not use webhooks to process when you receive incoming message (If you rely on incoming messages for something). If that's not the case, Then you could simply do something like:

Example:
 ```php
$telegram->setAsyncRequest(true);

$message = 'Test';
foreach($chat_ids as $chat_id) {
  $telegram->sendMessage($chat_id, $message);
}
```

So the above simply queues all the send message requests but won't actually make a call until it terminates. This way, it'll save your time and won't have to wait for it to process each request.

**Comment by codengine** [comment] 2015-07-22 07:37
You're right, but you (unfortunately) have to own a SSL certificate in order to use webhooks and they can be rather expensive ;). My suggestion is to provide a function to trigger the unwrap() mechanism, used in the __destroy() function, manually or expose some advanced functionality around the queue mechanism for messages.

**Comment by jonnywilliamson** [comment] 2015-07-22 07:51
@codengine - As a side note, https://www.startssl.com/ will give you a SSL cert for free. Currently using it on my project with no issues.

**Comment by irazasyed** [comment] 2015-07-22 10:30
@codengine I'll look into that for the next release.

As far as SSL is concerned, There is PositiveSSL which is inexpensive, there is also CloudFlare which gives you flexible SSL for free and as also suggested by @jonnywilliamson that's another one for free.

And in September, There's also this arriving: https://letsencrypt.org/ which looks fantastic.

**Comment by Decadence** [comment] 2016-09-28 13:09
@irazasyed Can you say why is this code not working?

```php

foreach ($telegram_users as $info) {
            Telegram::setAsyncRequest(true);

            $message = Telegram::sendMessage([
                "chat_id" => $info->chat_id,
                "text" => $message,
                "disable_web_page_preview" => true,
            ]);
}
```

With sync request all is fine.
With async PHP script just hangs.

**Comment by irazasyed** [comment] 2016-09-29 08:33
@Decadence Please create a new issue ticket along with details like how many telegram users you're trying to send this message to and version of the SDK you use.

**Comment by Decadence** [comment] 2016-09-29 09:11
@irazasyed https://github.com/irazasyed/telegram-bot-sdk/issues/255

**Comment by foremtehan** [comment] 2020-08-14 09:30
My version: 3.1.0

I'm 1000% sure async request not working correctly in all scenarios and i dont what the is the problem! cuz i cant event catch the error

In laravel project, When i set `setAsyncRequest(true)` in my listener class it not working, But as soon i remove it working properly , so i'm sure its not about my codes

**Comment by webnarmin** [comment] 2023-04-19 16:58
After some research a possible solution found:

```php

$api->setAsyncRequest(true);

$promises = [];
foreach ($message_ids as $message_id) {

    $promises[] = $api->getClient()->getHttpClientHandler()
        ->setTimeOut(5)
        ->setConnectTimeOut(5)
        ->send(
            $api->getClient()->getBaseBotUrl().$api->getAccessToken().'/deleteMessage',
            'POST',
            [
                'User-Agent' => 'Telegram Bot PHP SDK v'.Api::VERSION.' (https://github.com/irazasyed/telegram-bot-sdk)',
            ],
            [
                'form_params' => [
                    'chat_id' => $chat_id,
                    'message_id' => $message_id
                ]
            ],
            true
        );

}
GuzzleHttp\Promise\Utils::inspectAll($promises);

$api->setAsyncRequest(false);

```
